[package]
authors = ["Animesh Singh"]
name = "kikozip"
description = "Tool for extracting zip archives"
version = "0.2.1"
edition = "2024"

[dependencies]
zip = { version = "0.6", features = ["deflate", "aes-crypto"] }
encoding_rs = "0.8"
clap = { version = "4.1", features = ["derive"] }
